export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE'
export const ADD_ITEMS_REQUEST = 'ADD_ITEMS_REQUEST'
export const ADD_ITEMS_SUCCESS = 'ADD_ITEMS_SUCCESS'
export const ADD_ITEMS_FAILURE = 'ADD_ITEMS_FAILURE'
export const DELETE_ITEMS_REQUEST = 'DELETE_ITEMS_REQUEST'
export const DELETE_ITEMS_SUCCESS = 'DELETE_ITEMS_SUCCESS'
export const DELETE_ITEMS_FAILURE = 'DELETE_ITEMS_FAILURE'
export const UPDATE_ITEMS_REQUEST = 'UPDATE_ITEMS_REQUEST'
export const UPDATE_ITEMS_SUCCESS = 'UPDATE_ITEMS_SUCCESS'
export const UPDATE_ITEMS_FAILURE = 'UPDATE_ITEMS_FAILURE'


export const LIMIT = 3